In [6]:
import pandas as pd
import numpy as np
import os

In [19]:
cwd = os.path.abspath('')
files = os.listdir(cwd)

In [20]:
cwd

'C:\\Users\\SooHui.Ho\\Documents\\PSN\\SMU\\A_SMU\\PYTHON_Test'

In [30]:
files

['.ipynb_checkpoints',
 '2020-06-18_APAC_Project Pipeline Report_Template_SGPv1_Rohan.xlsx',
 '2020-06-18_APAC_Project Pipeline Report_Template_SGPv4_Li Koon.xlsx',
 '2020-06-18_Asean Project Pipeline Report_annie.xlsx',
 '2020-06-18_Asean Project Pipeline Report_EC.xlsx',
 '2020-06-18_BARTEC Malaysia - Pipeline Report 18 June 20.xlsx',
 '2020-06-18_Project Pipeline + Regional Report_AUGUSTINE.xlsx',
 '2020-06-18_Project Pipeline Report_Template - Bartec Indo.xlsx',
 '2020-06-18_Project Pipeline Report_Template_SGP(danny).xlsx',
 '2020-06-18__AMS_SG_Project Pipeline Report_Template_SGPv1_Vinod.xlsx',
 'Jupyter Notebook Viewer.html',
 'Jupyter Notebook Viewer_files',
 'Merging multiple excel sheet into one.pdf',
 'Others',
 'QuotationWeeklycompilation.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb']

In [31]:
df = pd.DataFrame()
for file in files:
     if file.endswith('.xlsx'):
         df = df.append(pd.read_excel(file,'Pipeline Report') ,ignore_index=True) 
df.head()

,Corporate interpretation,Probabilities for Active Projects,SGP intepretation,Sales Project Pipeline - MBR Review,Unnamed: 0,Unnamed: 1,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,...,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 8,Unnamed: 9,XXXX,x
0,NaN,0,NaN,Region:,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x
1,NaN,0.05,NaN,Country:,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x
2,NaN,0.3,NaN,Prepared by:,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x
3,NaN,0.5,NaN,Last updated on:,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x
4,NaN,0.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x